---
# Configure and enable the default virtual host for secure connections

- name: configure default SSL apache virtual host
  template: src=etc/apache2/sites-available/default-https-virtualhost.conf.j2 dest=/etc/apache2/sites-available/default-ssl.conf

- name: enable default SSL apache virtual host
  file: src=/etc/apache2/sites-available/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf state=link
  notify:
    - Restart Apache
