---
# Disable the default virtual host for non-secure connections

- name: disable default non-secure virtual host
  file: path=/etc/apache2/sites-enabled/default.conf state=absent
  notify:
    - Restart Apache
