---
# Disable the default virtual host for secure connections

- name: disable default secure virtual host
  file: path=/etc/apache2/sites-enabled/default-ssl.conf state=absent
  notify:
    - Restart Apache

- name: remove rule to allow secure connections to apache
  ufw: rule=allow name=Apache-Secure delete=yes
  when: apache_enable_feature_disable_default_apache_virtual_host == true or apache_enable_feature_disable_default_apache_virtual_host == "True"
