---
# Disable the default virtual host for secure connections

- name: disable default secure virtual host
  file: path=/etc/apache2/sites-enabled/default-ssl.conf state=absent
  notify:
    - Restart Apache
