---
# Disable the default apache virtual host for non-secure connections

- name: disable default apache non-secure virtual host
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - Restart Apache
