---

- name: install apache
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
    - apache2

- name: enable apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite
  notify:
    - Restart Apache