---
# Installs and configures apache web server

- include: install-apache.yml

- include: configure-apache.yml

- include: disable-default-configs.yml
  when: apache_enable_feature_disable_default_configs == true

- include: remove-default-content.yml
  when: apache_enable_feature_remove_default_document_root_content == true

- include: configure-ssl.yml
  when: apache_enable_feature_ssl == true

- include: app-user.yml

- include: configure-default-http-virtualhost.yml
  when: apache_enable_feature_default_http_virtualhost == true or apache_enable_feature_default_http_virtualhost == "True"

- include: configure-default-https-virtualhost.yml
  when: apache_enable_feature_default_https_virtualhost == true
