---
# Installs and configures apache web server

- include: install-apache.yml

- include: app-user.yml

- include: configure-ports.yml

- include: configure-default-virtualhost.yml

- include: configure-ssl.yml
  when: apache_default_var_www_ssl_enabled == true

- include: remove-default-content.yml
