---
# Installs and configures Apache web server and default virtual hosts

# Core configuration

- include: install-apache.yml

- include: configure-apache.yml

# Additional configuration

- include: disable-default-configs.yml
  when: apache_enable_feature_disable_default_configs == true

- include: remove-default-content.yml
  when: apache_enable_feature_remove_default_document_root_content == true

- include: configure-ssl.yml
  when: apache_enable_feature_ssl == true or apache_enable_feature_ssl == "True"

- include: app-user.yml

# Virtual hosts

- include: configure-default-http-virtualhost.yml
  when: apache_enable_feature_default_http_virtualhost == true or apache_enable_feature_default_http_virtualhost == "True"

- include: disable-default-http-virtualhost.yml
  when: apache_enable_feature_default_http_virtualhost == false or apache_enable_feature_default_http_virtualhost == "False"

- include: configure-default-https-virtualhost.yml
  when: apache_enable_feature_default_https_virtualhost == true or apache_enable_feature_default_https_virtualhost == "True"

- include: disable-default-https-virtualhost.yml
  when: apache_enable_feature_default_https_virtualhost == false or apache_enable_feature_default_https_virtualhost == "False"
